language: php

php:
    - 7.0
    - 7.1
    - 7.2

service:
    - mongodb

before_install: echo "extension = <extension>.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
    - pecl install mongodb
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script:
    - vendor/bin/phpstan analyse src tests --level 7
    - vendor/bin/phpunit tests/Unit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
