language: php

php:
    - 7.0
    - 7.1
    - 7.2

service:
    - mongodb

before_install: echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
    - pecl install -f mongodb

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev
    # Start Mongo
    - sudo service mongod start
    - sleep 5
    # Set up PHP server
    - cd public
    - php -S 127.0.0.1:8000 >/dev/null 2>&1 &
    - sleep 5
    - cd ../
    # Make .env file for tests
    - touch .env
    - echo "DEVELOPMENT=true" >> .env
    - echo "TOKEN_SECRET=abcD$1234!ef56" >> .env
    - echo "TOKEN_EXPIRY=2" >> .env
    - echo "TOKEN_ISSUER=mongolium" >> .env
    - echo "MONGO_HOST=localhost" >> .env
    - echo "MONGO_PORT=27017" >> .env
    - echo "MONGO_DATABASE=test" >> .env
    - echo "TEST_HOST=127.0.0.1" >> .env
    - echo "TEST_PORT=8000" >> .env
    - sleep 5

script:
    - vendor/bin/phpstan analyse -l 7 -c phpstan.neon tests src public
    - vendor/bin/phpmd src text ruleset.xml
    - vendor/bin/phpunit --coverage-clover=coverage.xml tests/Core/Unit
    - vendor/bin/phpunit tests/Core/Feature

after_success:
    - bash <(curl -s https://codecov.io/bash)
