env:
    - DEVELOPMENT=true
    - TOKEN_SECRET="abcD$1234!ef56"
    - TOKEN_EXPIRY=2
    - TOKEN_ISSUER=mongolium
    - MONGO_HOST="localhost"
    - MONGO_PORT=27017
    - MONGO_DATABASE="test"

language: php

php:
    - 7.0
    - 7.1
    - 7.2

service:
    - mongodb

before_install: echo "extension = <extension>.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
    - pecl install -f mongodb

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev
    # Set up PHP server
    - cd public
    - php -S 127.0.0.1:8000 >/dev/null 2>&1 &
    - sleep 3
    - cd ../

script:
    - vendor/bin/phpstan analyse -l 7 -c phpstan.neon tests src public
    - vendor/bin/phpunit --coverage-clover=coverage.xml tests/Unit
    - vendor/bin/phpunit tests/Feature

after_success:
    - bash <(curl -s https://codecov.io/bash)
