#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

$dotenv = new Dotenv\Dotenv(__DIR__);
$dotenv->load();

use Mongolium\Core\Services\Db\Orm;
use Mongolium\Core\Exceptions\OrmException;
use Mongolium\Core\Services\Db\Client;
use Mongolium\Core\Services\Admin;

$orm = new Orm(
    Client::getInstance(getenv('MONGO_HOST'), getenv('MONGO_PORT'), getenv('MONGO_DATABASE'))
);

$adminService = new Admin($orm);

$admin = [
    'username' => 'admin',
    'password' => 'helloWorld123!',
    'email' => 'test@test.com',
    'first_name' => 'Admin',
    'last_name' => 'Admin',
    'type' => 'super-admin'
];

try {
    $result = $adminService->create($admin);

    $extract = $result->extract();

    echo "User generated with username:password \33[32m" . $extract['username'] . ':' . $extract['password'] . "\33[0m" . PHP_EOL;
} catch (OrmException $e) {
    echo "\33[31mAdmin user already exists\33[0m, cannot generate again." . PHP_EOL;
}
